version: '3.8'
networks:
    petstore-network:
        name: petstore-network

services:
  # Postgres database
  postgres:
    image: postgres
    container_name: pg-petstore
    restart: on-failure
    profiles:
      - all
      - postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=pet-store-db
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - postgres:/var/log/postgres
    networks:
      - petstore-network

  # Minio server for file storage (pet images)
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio-petstore
    restart: on-failure
    hostname: minio
    profiles:
      - all
      - minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
      - MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
      - MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - petstore-network

volumes:
  postgres:
  minio_data:
    driver: local
  postgres-data:
    driver: local